[tool.poetry]
name = "myblog"
version = "0.1.0"
description = ""
authors = ["Ales <rybij1984@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
