# Generated by Django 4.2 on 2023-05-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='images/%Y', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
